//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSafehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLActionItem
    {
        public SQLActionItem()
        {
            this.ActionItemUsers = new HashSet<SQLActionItemUser>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.Guid InReleaseId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid CurrentStatusId { get; set; }
        public System.Guid ActionItemTypeId { get; set; }
        public Nullable<long> Estimate { get; set; }
        public Nullable<long> TimeSpent { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> IndividualTargetDate { get; set; }
        public int CurrentPriority { get; set; }
    
        public virtual SQLActionItemType ActionItemType { get; set; }
        public virtual SQLStatus Status { get; set; }
        public virtual SQLRelease Release { get; set; }
        public virtual ICollection<SQLActionItemUser> ActionItemUsers { get; set; }
    }
}
