//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectArsenal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLActionItemUser
    {
        public int ID { get; set; }
        public System.Guid ActionItemId { get; set; }
        public System.Guid AssignedToUserID { get; set; }
    
        public virtual SQLActionItem ActionItem { get; set; }
        public virtual SQLUser User { get; set; }
    }
}
