//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectArsenal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLCompanyUser
    {
        public int ID { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> AddedBy { get; set; }
        public int RoleId { get; set; }
    
        public virtual SQLCompany Company { get; set; }
        public virtual SQLSystemRole SystemRole { get; set; }
        public virtual SQLUser User { get; set; }
        public virtual SQLUser User1 { get; set; }
    }
}
