//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSafehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLCompanyPriority
    {
        public int ID { get; set; }
        public System.Guid CompanyId { get; set; }
        public int PriorityNumber { get; set; }
        public string PriorityName { get; set; }
    
        public virtual SQLCompany Company { get; set; }
    }
}
