//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSafehouse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectSafehouseEntities : DbContext
    {
        public ProjectSafehouseEntities()
            : base("name=ProjectSafehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SQLUser> SQLUsers { get; set; }
        public DbSet<SQLCompany> SQLCompanies { get; set; }
        public DbSet<SQLProject> SQLProjects { get; set; }
        public DbSet<SQLRelease> SQLReleases { get; set; }
    }
}
