//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSafehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLProject
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CompanyId { get; set; }
    
        public virtual SQLCompany Company { get; set; }
        public virtual SQLUser User { get; set; }
    }
}
